feat: add navbar
KATITB2023/oskm-info pull request #22
Opened 2023-07-25 22:15 UTC by zen87-byte

## Story/Task
https://trello.com/c/IsEr0Qef

## Summary
- Create responsive Navbar

## Screenshot
<img width="860" alt="Screenshot 2023-07-26 at 05 11 18" src="https://github.com/KATITB2023/oskm-info/assets/109773467/5b44ab5f-2269-4139-96fc-5d2055cdb05e">
<img width="389" alt="Screenshot 2023-07-26 at 05 09 54" src="https://github.com/KATITB2023/oskm-info/assets/109773467/23dbd7f1-d7f5-442e-be85-b517a89eee03">
<img width="388" alt="Screenshot 2023-07-26 at 05 10 13" src="https://github.com/KATITB2023/oskm-info/assets/109773467/cdcf76f1-db23-4003-b5b5-4a552542a3c2">

2023-07-27 09:05 UTC, msyahrulsp requested changes
ubah dlu ya

2023-07-27 09:05 UTC, msyahrulsp commented on src/components/Navbar.tsx
> +                    </svg>
PIndah aja as file svg

2023-07-27 09:05 UTC, msyahrulsp commented on src/components/Navbar.tsx
> +                    </svg>
Pindah aja as file svg

2023-07-27 09:05 UTC, msyahrulsp commented on src/components/Navbar.tsx
> +                    </svg>
Pindah aja as file svg

2023-07-27 09:05 UTC, msyahrulsp commented on src/components/Navbar.tsx
> +                    </svg>
Pindah aja as file svg

2023-07-27 09:05 UTC, msyahrulsp commented on src/components/Navbar.tsx
> +          <Image src='/images/nav-ekor.png' />
```suggestion
          <Image src='/images/nav-ekor.png' draggable='false' loading='lazy' />
```

2023-07-27 09:05 UTC, msyahrulsp commented on src/components/Navbar.tsx
> +          />
```suggestion
          <Image
            src='/images/nav-logo.svg'
            height={{ base: '38px', lg: '57px' }}
            draggable='false'
            loading='lazy'
          />
```

2023-07-27 09:05 UTC, msyahrulsp commented on src/components/Navbar.tsx
> +              <Image src='/images/hamburger.png' width='24px' margin='auto' />
```suggestion
              <Image src='/images/hamburger.png' width='24px' margin='auto' draggable='false' loading='lazy' />
```

2023-07-27 09:07 UTC, msyahrulsp commented
UI-nya dah mantap, boleh sekalian tambahin aja ke `index.tsx` di layout

2023-07-29 06:58 UTC, msyahrulsp requested changes
Dah oke yang lain, paling sekalian resolve sama staging. Bisa aja gini langsung

> git checkout staging package.json
> git checkout staging yarn.lock

2023-07-29 06:58 UTC, msyahrulsp commented on src/layout/index.tsx
>    title: string;
Titip benerin ini
```suggestion
  title?: string;
```

2023-07-29 06:58 UTC, msyahrulsp commented on src/components/Navbar.tsx
> +      >
coba navbarnya dibuat sticky, supaya pas dipake, childrennya otomatis ada dibawah navbarnya

2023-07-29 06:58 UTC, msyahrulsp commented on src/components/Navbar.tsx
> +        <Box display={{ base: 'block', lg: '' }} >
```suggestion
        <Box display={{ base: 'block', lg: 'none' }} >
```

di test jadi gini soalnya
![image](https://github.com/KATITB2023/oskm-info/assets/65522975/04277eb6-45b3-4bbd-b5e0-924cd09792b1)

2023-07-29 13:37 UTC, zen87-byte commented on src/components/Navbar.tsx
> +        <Box display={{ base: 'block', lg: '' }} >
oiya lupa blm dibuat none lagi

2023-07-30 04:38 UTC, msyahrulsp approved these changes
LGTM

2023-07-30 04:38 UTC, merged