fix: remove redundant styles, add lazy loading, rework login form width and spacing, add toast after submission, move form to components
KATITB2023/oskm-info pull request #25
Opened 2023-07-27 12:58 UTC by soezyxst

## Story/Task

[_Link ke story/task di Trello_](https://trello.com/c/bitc4f8t)

## Summary

- _Remove redundant styles_
- _Add lazy loading_
- _Rework login form width and spacing_
- _Add toast after submission_
- _Move form component to folder components_

## Screenshot

### SS on dekstop

_normal_

![image](https://github.com/KATITB2023/oskm-info/assets/110209279/87b1b3c0-0ceb-45bb-8e2e-d06736bf68c7)

_user not found_

![image](https://github.com/KATITB2023/oskm-info/assets/110209279/75dcd74d-416a-42d9-8349-8f6402f048b8)

_password is incorrect_

![image](https://github.com/KATITB2023/oskm-info/assets/110209279/3c02c0cc-e61e-49bd-9738-042664541db2)

_success_

![image](https://github.com/KATITB2023/oskm-info/assets/110209279/090f294b-054c-4507-8670-037205c83515)

### SS on mobile

![image](https://github.com/KATITB2023/oskm-info/assets/110209279/17c687c2-2b34-414b-aa57-e033a5f0c99b)

2023-07-28 02:58 UTC, msyahrulsp requested changes
Boleh diubah dlu. PR yang sekarang gk perlu di close

Langsung aja update di branch kamu terus update, nanti PR ini otomatis ke-update

2023-07-28 02:58 UTC, msyahrulsp commented on src/components/form/LoginForm.tsx
> +      }
Ini ga perlu pake `setError` dari `react-hook-form`. Karena udah pake `toast` juga buat munculin error dari backend

2023-07-28 02:58 UTC, msyahrulsp commented on src/components/form/LoginForm.tsx
> +          </Button>
```suggestion
          <Button
            type='submit'
            isDisabled={!isDirty || !isValid}
            isLoading={isSubmitting}
            loadingText='Loading...'
            maxW='12rem'
            w='100%'
            fontFamily='Bodwars'
            cursor='pointer'
            size={{ base: 'sm', md: 'md' }}
          >
            Login
          </Button>
```

2023-07-28 03:56 UTC, soezyxstt commented on src/components/form/LoginForm.tsx
> +      }
oke siap kak

2023-07-28 03:56 UTC, soezyxstt commented on src/components/form/LoginForm.tsx
> +          </Button>
iya ini kemarin baru baca ada isLoading sama disabled katanya ga bisa dan harus jadi isDisabled

2023-07-29 06:27 UTC, msyahrulsp requested changes
Sisa 2 itu yaa

2023-07-29 06:27 UTC, msyahrulsp commented on src/components/form/LoginForm.tsx
> +                placeholder='password'
```suggestion
                placeholder='Password'
```

2023-07-29 06:27 UTC, msyahrulsp commented on src/components/form/LoginForm.tsx
> +                type={showPassword ? 'text' : 'password'}
Dibalik yes
```suggestion
                type={showPassword ? 'password' : 'text'}
```

2023-07-29 07:00 UTC, soezyxst commented on src/components/form/LoginForm.tsx
> +                type={showPassword ? 'text' : 'password'}
ini default value statenya dibalik juga kak?

2023-07-29 09:26 UTC, msyahrulsp commented on src/components/form/LoginForm.tsx
> +                type={showPassword ? 'text' : 'password'}
iya juga. kalau gitu, yang dibalik itu dibagian iconnya aja ya. yg tipe input sama default valuenya didiemin 👌

2023-07-29 09:28 UTC, soezyxst commented on src/components/form/LoginForm.tsx
> +                type={showPassword ? 'text' : 'password'}
oke siap kak

2023-07-31 04:28 UTC, closed without merging