Feat/about us
KATITB2023/oskm-info pull request #38
Opened 2023-08-06 14:57 UTC by ashnchiquita

## Story/Task

[Trello](https://trello.com/c/5QEm0shL/30-fe-oskm-history-page)

## Summary

- About us yang responsif

## Screenshot
### Desktop

![About Us - OSKM ITB 2023-1](https://github.com/KATITB2023/oskm-info/assets/88751131/790b1fb6-ae2c-4c70-8dc5-aab323c479be)

![Screen Shot 2023-08-06 at 21 33 16](https://github.com/KATITB2023/oskm-info/assets/88751131/fa4718c7-0342-40e5-ab8c-a20d31007290)

### Mobile
![About Us - OSKM ITB 2023-mobile-1](https://github.com/KATITB2023/oskm-info/assets/88751131/eef118db-720f-4873-8bbf-09d0aee07905)
![Screen Shot 2023-08-06 at 21 33 44](https://github.com/KATITB2023/oskm-info/assets/88751131/9785f843-c774-450e-b9d1-46827980f965)

2023-08-07 01:29 UTC, msyahrulsp requested changes
- File yang size >1mb itu dah dicompress kah??
- Kalau asset yang ada desktop dan mobile terus gambarnya sama, samain aja (jadi ga perlu ada file prefix `-mobile`)
- Itu yg read more, kalau dah dibuka, bisa dibikin ditutup lagi kah? cukup tambah icon x aja

2023-08-07 01:31 UTC, msyahrulsp commented on src/pages/about-us/VisMis.tsx
> +          right='-50px'
Ini jangan -50px, pas mobile break

2023-08-07 12:38 UTC, ashnchiquita commented
icon close nya taro di mana kak? di kotak yang periode bla bla itu apa di luarnya?

2023-08-08 02:04 UTC, msyahrulsp commented
> icon close nya taro di mana kak? di kotak yang periode bla bla itu apa di luarnya?

di kotak yg periodenya aja chi

2023-08-08 14:44 UTC, msyahrulsp commented
Tolong ini juga chi, fontsize yang visi misi perbesar, biar keliatannya ga terlalu kosong (desktop)

2023-08-08 20:49 UTC, msyahrulsp commented
`HistoryCarousel` sama `VisMis` pindah ke komponen, jangan di pages. Bisa diakses orang soalnya

2023-08-09 11:28 UTC, ashnchiquita commented
kak udah ya yang sisanya ada prefix -mobile cuman yang ada di mobile aja

2023-08-10 08:55 UTC, msyahrulsp approved these changes
LGTM!

2023-08-10 08:55 UTC, merged